language: cpp
compiler: gcc
os: linux
dist: bionic

before_script:
    - sudo apt-get update
    - sudo apt-get install -y libcppunit-dev lcov
    - mkdir .aux_deps
    - wget https://root.cern/download/root_v6.18.02.Linux-ubuntu18-x86_64-gcc7.4.tar.gz
    - tar zxf root_v6.18.02.Linux-ubuntu18-x86_64-gcc7.4.tar.gz -C .aux_deps
    - . ./.aux_deps/root/bin/thisroot.sh
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake .. -DCODE_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug
script:
    - make
    - make test
before_install:
    - pip install --user cpp-coveralls
after_success:
    - cd ..
    - coveralls -r . -b build -E ".*/build/.*" -E ".*/tests/.*" -E ".*/cmake-scripts/.*" --gcov-options "\-lp"
